from __future__ import annotations
import asyncio
import json
import subprocess
from pathlib import Path

import click

from campsite.config import load_config


@click.group()
def cli():
    """BC Parks campsite scanner and auto-booker."""
    pass


@cli.command()
def discover():
    """
    Record BC Parks API calls and booking flow from a live browser session.

    Phase 1: Browse the site normally while network traffic is recorded.
    Phase 2: Go through checkout while your clicks are recorded as Playwright code.

    Output: docs/api-notes.md and docs/booking-flow.py
    """
    asyncio.run(_run_discover())


async def _run_discover() -> None:
    from playwright.async_api import async_playwright

    docs = Path("docs")
    docs.mkdir(exist_ok=True)

    api_calls: list[dict] = []

    click.echo("=== Phase 1: API Discovery ===")
    click.echo("A browser window will open. Browse normally:")
    click.echo("  1. Search for a campground")
    click.echo("  2. Select dates and view available sites")
    click.echo("  3. Add a site to cart and go through checkout")
    click.echo("  4. Stop before entering payment")
    click.echo("\nAll API calls are recorded automatically.")
    click.echo("Press Enter here when you are done browsing...\n")

    async with async_playwright() as p:
        browser = await p.chromium.launch(headless=False)
        context = await browser.new_context()
        page = await context.new_page()

        response_bodies: dict[str, object] = {}

        async def on_response(response):
            if response.request.resource_type in ("xhr", "fetch"):
                try:
                    body = await response.json()
                except Exception:
                    try:
                        body = await response.text()
                    except Exception:
                        body = None
                response_bodies[response.url] = body

        page.on("response", on_response)

        page.on(
            "request",
            lambda req: api_calls.append({
                "url": req.url,
                "method": req.method,
                "resource_type": req.resource_type,
                "headers": dict(req.headers),
                "post_data": req.post_data,
            }) if req.resource_type in ("xhr", "fetch") else None,
        )

        await page.goto("https://camping.bcparks.ca")
        input()

        await context.close()
        await browser.close()

    for call in api_calls:
        call["response"] = response_bodies.get(call["url"])

    lines = [
        "# BC Parks API Notes\n\n",
        "_Generated by `campsite discover`. Edit to add implementation notes._\n\n",
    ]
    for call in api_calls:
        lines.append(f"## {call['method']} {call['url']}\n\n")
        if call.get("post_data"):
            lines.append(f"**Request body:**\n```\n{call['post_data']}\n```\n\n")
        if call.get("response"):
            body = call["response"]
            formatted = json.dumps(body, indent=2) if isinstance(body, (dict, list)) else str(body)
            lines.append(f"**Response:**\n```json\n{formatted[:2000]}\n```\n\n")

    notes_path = docs / "api-notes.md"
    notes_path.write_text("".join(lines))
    click.echo(f"API notes saved to {notes_path}")

    click.echo("\n=== Phase 2: Booking Flow Recording ===")
    click.echo("A new browser window will open.")
    click.echo("Go through the COMPLETE checkout including payment.")
    click.echo("Close the browser window when done.\n")

    flow_path = docs / "booking-flow.py"
    subprocess.run(
        ["playwright", "codegen", "--output", str(flow_path), "https://camping.bcparks.ca"],
        check=False,
    )
    click.echo(f"Booking flow saved to {flow_path}")
    click.echo("\nDiscovery complete. Review docs/api-notes.md and docs/booking-flow.py,")
    click.echo("then implement campsite/api.py and campsite/booker.py.")


@cli.command()
@click.option("--file", "config_file", default="config.yaml", show_default=True,
              type=click.Path(exists=True), help="Path to config.yaml")
def check(config_file: str) -> None:
    """One-shot availability check across all configured campgrounds and dates. Does not book."""
    config = load_config(Path(config_file))
    asyncio.run(_run_check(config))


async def _run_check(config) -> None:
    from campsite.api import BCParksAPI
    from campsite.scanner import Scanner

    api = BCParksAPI()
    try:
        scanner = Scanner(config, api)
        match = await scanner.run_once()
        if match:
            click.echo(
                f"Available: {match.campground_id} | {match.check_in} → {match.check_out}"
                f" | site {match.site_id}"
            )
        else:
            click.echo("No availability found for your campgrounds and dates.")
    finally:
        await api.close()


@cli.command()
@click.option("--file", "config_file", default="config.yaml", show_default=True,
              type=click.Path(exists=True), help="Path to config.yaml")
def scan(config_file: str) -> None:
    """
    Start the polling loop. Scans for availability, books the first match, then stops.
    Runs until a campsite is successfully booked or you press Ctrl+C.
    """
    config = load_config(Path(config_file))
    asyncio.run(_run_scan(config))


async def _run_scan(config) -> None:
    from campsite.api import BCParksAPI
    from campsite.scanner import Scanner
    from campsite.booker import book_site
    from campsite.notifier import notify, NotificationEvent

    api = BCParksAPI()
    scanner = Scanner(config, api)

    click.echo(f"Scanning every {config.poll_interval_seconds}s. Press Ctrl+C to stop.")

    async def on_match(site) -> bool:
        notify(
            NotificationEvent(
                title="Campsite Available!",
                message=(
                    f"{site.campground_id} | {site.check_in} → {site.check_out}"
                    f" | site {site.site_id}"
                ),
            ),
            config.notifications,
        )
        if not config.auto_book:
            click.echo("auto_book is false — not booking. Continuing to scan.")
            return False

        click.echo("Attempting to book...")
        result = await book_site(site, config)

        if result.success:
            notify(
                NotificationEvent(
                    title="Booking Confirmed!",
                    message=(
                        f"Confirmation: {result.confirmation_number}"
                        f" | {site.check_in} → {site.check_out}"
                    ),
                ),
                config.notifications,
            )
            return True
        elif result.error_message and "payment" in result.error_message.lower():
            notify(
                NotificationEvent(
                    title="Payment Failed — Action Required",
                    message=(
                        f"{result.error_message}"
                        " — scanning paused. Restart campsite scan to resume."
                    ),
                ),
                config.notifications,
            )
            raise SystemExit(1)
        else:
            notify(
                NotificationEvent(
                    title="Booking Failed",
                    message=f"{result.error_message} — trying next campground",
                ),
                config.notifications,
            )
            return False

    try:
        await scanner.run_loop(on_match)
        click.echo("Done — campsite booked successfully.")
    except KeyboardInterrupt:
        click.echo("\nScan stopped.")
    finally:
        await api.close()


@cli.group("config")
def config_group() -> None:
    """Config management commands."""
    pass


@config_group.command("check")
@click.option("--file", "config_file", default="config.yaml", show_default=True,
              type=click.Path(exists=True), help="Path to config.yaml")
def config_check(config_file: str) -> None:
    """Validate config.yaml without running the scanner."""
    try:
        load_config(Path(config_file))
        click.echo("Config is valid.")
    except Exception as e:
        click.echo(f"Config error: {e}", err=True)
        raise SystemExit(1)
